apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taxi-fare-predictor
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: local-mlops-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mayank-gokarna/ml-workflow.git
    targetRevision: main
    path: local-mlops-platform/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
