apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    app.kubernetes.io/part-of: local-mlops-platform
    # Enable metrics scraping conventions for this namespace.
    monitoring: "true"
